import {useStore} from '../state/store';
import type {ModelContextTool} from './api';
const tool=(name:string,title:string,description:string,inputSchema:Record<string,unknown>|undefined,execute:ModelContextTool['execute'],readOnlyHint=false,untrustedContentHint=false):ModelContextTool=>({name,title,description,inputSchema,execute,annotations:{readOnlyHint,untrustedContentHint}});
export async function registerAllTools(signal:AbortSignal){const mc=document.modelContext;if(!mc) return; const tools:ModelContextTool[]=[
 tool('get_inventory','Get Inventory','Return every listed item with id, title, category, asking price, condition, and status. Use before pricing or bundling.',undefined,async()=>useStore.getState().inventory.map(({id,title,category,ask,condition,status})=>({id,title,category,ask,condition,status})),true,true),
 tool('set_price','Set Item Price','Set one seller item asking price in USD after checking comps. Returns the updated item and logs the reason.',{type:'object',properties:{item_id:{type:'string'},price:{type:'number'},reason:{type:'string'}},required:['item_id','price']},async({item_id,price,reason})=>{const item=useStore.getState().setItemPrice(item_id,price,reason);if(!item)throw new Error(`Unknown item_id: ${item_id}`);return{ok:true,item};}),
 tool('create_bundle','Create Bundle','Group two or more inventory items at a 1–70% discount. Returns the created bundle.',{type:'object',properties:{item_ids:{type:'array',items:{type:'string'}},discount_percent:{type:'number'}},required:['item_ids','discount_percent']},async({item_ids,discount_percent})=>useStore.getState().createBundle(item_ids,discount_percent)),
 tool('get_offers','Get Open Offers','Return all open and countered buyer offers with persona, items, amount, round, and expiry.',undefined,async()=>useStore.getState().offers.filter(o=>o.status==='open'||o.status==='countered'),true,true),
 tool('respond_to_offer','Respond To Offer','Accept, reject, or counter a buyer offer. Accept moves it to pending_approval; a human must click Approve in the Deal Tray.',{type:'object',properties:{offer_id:{type:'string'},action:{type:'string',enum:['accept','reject','counter']},counter_amount:{type:'number'}},required:['offer_id','action']},async({offer_id,action,counter_amount})=>{const offer=useStore.getState().respond(offer_id,action,counter_amount);return{ok:true,offer,message:action==='accept'?'Awaiting human approval — click Approve in the Deal Tray.':undefined};}),
 tool('send_message','Message Buyer','Send a free-form message to a buyer persona; returns the simulated persona reply in the negotiation feed.',{type:'object',properties:{persona:{type:'string',enum:['Lowball Larry','Bundle Bella','Flash Frank']},message:{type:'string'}},required:['persona','message']},async({persona,message})=>{useStore.getState().addMessage(persona,message);return{ok:true,persona};},false,true),
 tool('get_negotiation_log','Get Negotiation Log','Return the full timestamped negotiation transcript for agent context.',undefined,async()=>useStore.getState().feed,true,true),
 tool('get_analytics','Get Analytics','Return projected monthly earnings, average accepted amount, open offers, deals won/lost, and suggested reprice candidates.',undefined,async()=>useStore.getState().analytics(),true),
 tool('approve_pending_deal','Approve Pending Deal','Finalize a pending deal only when the human clicked Approve in the UI within the last 60 seconds; otherwise explain that approval is awaiting the user.',{type:'object',properties:{deal_id:{type:'string'}},required:['deal_id']},async({deal_id})=>useStore.getState().approveDeal(deal_id)?{ok:true,message:'Deal approved and inventory marked sold.'}:{ok:false,message:'Awaiting human approval — the user must click Approve in the Deal Tray.'})];
 for(const current of tools){try{await mc.registerTool(current,{signal});}catch(err){console.warn(`[WebMCP] ${current.name} failed:`,err);}}
}
