import { useEffect, useMemo, useState } from 'react';
import { useStore } from './state/store';
import { useWebMCP } from './webmcp/useWebMCP';
import { startBuyerEngine, stopBuyerEngine } from './agents/engine';
import type { Offer } from './types';

const money = (value: number) => `$${Math.round(value).toLocaleString()}`;
const personaMeta: Record<string, { emoji: string; color: string }> = {
  'Lowball Larry': { emoji: '🧢', color: '#F0A83B' },
  'Bundle Bella': { emoji: '✨', color: '#F0A83B' },
  'Flash Frank': { emoji: '⚡', color: '#F0A83B' },
};

function App() {
  const { available, ready } = useWebMCP();
  const inventory = useStore((state) => state.inventory);
  const offers = useStore((state) => state.offers);
  const feed = useStore((state) => state.feed);
  const pendingDeals = useStore((state) => state.pendingDeals);
  const respond = useStore((state) => state.respond);
  const setItemPrice = useStore((state) => state.setItemPrice);
  const markHumanApproval = useStore((state) => state.markHumanApproval);
  const approveDeal = useStore((state) => state.approveDeal);
  const rejectDeal = useStore((state) => state.rejectDeal);
  const [query, setQuery] = useState('');
  const [priceId, setPriceId] = useState<string>();
  const [priceInput, setPriceInput] = useState('');
  const [counterInput, setCounterInput] = useState<Record<string, string>>({});
  const [notice, setNotice] = useState('');
  const [inspector, setInspector] = useState(false);
  const [tools, setTools] = useState<any[]>([]);
  const [selectedTool, setSelectedTool] = useState('');
  const [toolInput, setToolInput] = useState('{}');
  const [toolResult, setToolResult] = useState('');

  useEffect(() => { startBuyerEngine(); return stopBuyerEngine; }, []);
  useEffect(() => { if (document.modelContext) document.modelContext.getTools().then((items) => setTools(items as any[])).catch(() => undefined); }, [ready]);
  useEffect(() => { if (!notice) return; const timer = window.setTimeout(() => setNotice(''), 3000); return () => window.clearTimeout(timer); }, [notice]);
  useEffect(() => { const close = (event: KeyboardEvent) => event.key === 'Escape' && setInspector(false); window.addEventListener('keydown', close); return () => window.removeEventListener('keydown', close); }, []);

  const openOffers = useMemo(() => offers.filter((offer) => offer.status === 'open' || offer.status === 'countered').sort((a, b) => b.createdAt - a.createdAt), [offers]);
  const currentOffer = openOffers[0];
  const filteredInventory = useMemo(() => inventory.filter((item) => item.title.toLowerCase().includes(query.toLowerCase()) || item.category.toLowerCase().includes(query.toLowerCase())), [inventory, query]);
  const visibleFeed = useMemo(() => [...feed].sort((a, b) => a.timestamp - b.timestamp), [feed]);
  const currentAsk = currentOffer ? currentOffer.items.reduce((total, id) => total + (inventory.find((item) => item.id === id)?.ask ?? 0), 0) : 0;
  const delta = currentOffer ? currentOffer.amount - currentAsk : 0;
  const activeDeal = pendingDeals[0];

  const notify = (message: string) => setNotice(message);
  const savePrice = (id: string) => { const value = Number(priceInput); if (!Number.isFinite(value) || value <= 0) return notify('Enter a valid price above $0.'); try { setItemPrice(id, value); setPriceId(undefined); notify('Price updated.'); } catch (error) { notify(error instanceof Error ? error.message : 'Price update failed.'); } };
  const sendCounter = (offer: Offer) => { const value = Number(counterInput[offer.id]); if (!Number.isFinite(value) || value <= 0) return notify('Enter a valid counter amount.'); try { respond(offer.id, 'counter', value); notify(`Counter sent to ${offer.persona}.`); } catch (error) { notify(error instanceof Error ? error.message : 'Counter failed.'); } };
  const accept = (offer: Offer) => { try { respond(offer.id, 'accept'); notify('Offer accepted. Human approval is required below.'); } catch (error) { notify(error instanceof Error ? error.message : 'Accept failed.'); } };
  const decline = (offer: Offer) => { try { respond(offer.id, 'reject'); notify('Offer declined.'); } catch (error) { notify(error instanceof Error ? error.message : 'Decline failed.'); } };
  const approve = (id: string) => { markHumanApproval(id); notify(approveDeal(id) ? 'Deal approved.' : 'Approval window expired.'); };
  const selectTool = (name: string) => { setSelectedTool(name); const offer = currentOffer; const deal = activeDeal; const sample: Record<string, unknown> = { get_inventory: {}, get_offers: {}, get_analytics: {}, get_negotiation_log: {}, set_price: { item_id: inventory[0]?.id, price: inventory[0]?.ask, reason: 'Inspector sample' }, create_bundle: { item_ids: inventory.slice(0, 2).map((item) => item.id), discount_percent: 15 }, respond_to_offer: { offer_id: offer?.id ?? 'off_example', action: 'counter', counter_amount: offer?.amount ? offer.amount + 10 : 100 }, send_message: { persona: 'Bundle Bella', message: 'Can you improve the bundle?' }, approve_pending_deal: { deal_id: deal?.id ?? 'deal_example' } }; setToolInput(JSON.stringify(sample[name] ?? {}, null, 2)); setToolResult(''); };
  const executeTool = async () => { if (!document.modelContext || !selectedTool) return; const tool = tools.find((item) => item.name === selectedTool); if (!tool) return; let input: object; try { input = JSON.parse(toolInput) as object; } catch { setToolResult('Invalid JSON.'); return; } try { setToolResult(await document.modelContext.executeTool(tool, input)); } catch (firstError) { try { setToolResult(await document.modelContext.executeTool(tool, JSON.stringify(input))); } catch (secondError) { setToolResult(secondError instanceof Error ? secondError.message : firstError instanceof Error ? firstError.message : String(secondError)); } } };

  return <div className="min-h-screen bg-[#0E0F11] px-4 py-5 text-[#E8E6E1] md:px-8 md:py-7">
    <header className="mx-auto mb-5 flex max-w-[1440px] items-center justify-between gap-4"><div><p className="mb-2 text-[13px] text-[#8B8D91]">Agent-powered resale desk</p><h1 className="text-3xl font-semibold tracking-[-.05em] md:text-4xl">barg<span className="text-[#F0A83B]">ai</span>ner</h1></div><div className="flex items-center gap-3"><span className="hidden text-[13px] text-[#8B8D91] sm:inline">{ready ? 'WebMCP connected' : available ? 'Registering tools' : 'Local fallback'}</span><span className={`h-2 w-2 rounded-full ${ready ? 'bg-[#3DDC84]' : 'bg-[#F0A83B]'}`} /><button onClick={() => setInspector(true)} className="rounded-lg border border-[#2A2D31] bg-[#1A1C1F] px-3 py-2 text-[13px] text-[#E8E6E1] hover:bg-[#232629]">Inspect tools</button></div></header>
    {!available && <div className="mx-auto mb-5 max-w-[1440px] border-b border-[#2A2D31] pb-3 text-[13px] text-[#8B8D91]">WebMCP is unavailable here. The desk remains fully usable; enable the WebMCP testing flag for agent control.</div>}
    <main className="bento mx-auto max-w-[1440px]">
      <section className="bento-feed rounded-xl border border-[#2A2D31] bg-[#1A1C1F] p-4 md:p-6"><div className="mb-5 flex items-start justify-between"><div><p className="text-[13px] text-[#8B8D91]">Live negotiation</p><h2 className="mt-1 text-xl font-semibold">Agent-to-agent room</h2></div><span className="flex items-center gap-2 text-[13px] text-[#8B8D91]"><span className="h-2 w-2 rounded-full bg-[#3DDC84]" />Live</span></div><div className="feed-scroll space-y-4">{visibleFeed.map((event) => <FeedMessage key={event.id} event={event} offers={offers} counterInput={counterInput} setCounterInput={(id, value) => setCounterInput((current) => ({ ...current, [id]: value }))} accept={accept} decline={decline} sendCounter={sendCounter} />)}</div></section>
      <section className="bento-inventory rounded-xl border border-[#2A2D31] bg-[#1A1C1F] p-4"><div className="mb-3 flex items-center justify-between"><div><p className="text-[13px] text-[#8B8D91]">Your inventory</p><h2 className="mt-1 text-xl font-semibold">Listings</h2></div><span className="mono text-[13px] text-[#8B8D91]">{filteredInventory.length}/{inventory.length}</span></div><input aria-label="Search inventory" value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search items" className="mb-3 w-full rounded-lg border border-[#2A2D31] bg-[#0E0F11] px-3 py-2 text-[13px] text-[#E8E6E1] placeholder:text-[#8B8D91]"/><div className="inventory-scroll space-y-1">{filteredInventory.map((item) => <div key={item.id} className="flex items-center justify-between gap-2 rounded-lg bg-[#232629] px-3 py-2.5"><div className="min-w-0"><p className="truncate text-[15px]">{item.title}</p><p className="text-[13px] text-[#8B8D91]">{item.condition} · {item.status}</p></div>{priceId === item.id ? <div className="flex shrink-0 gap-1"><input aria-label="New price" autoFocus value={priceInput} onChange={(event) => setPriceInput(event.target.value)} className="mono w-16 rounded border border-[#2A2D31] bg-[#0E0F11] px-1.5 py-1 text-xs"/><button onClick={() => savePrice(item.id)} className="rounded bg-[#3DDC84] px-2 py-1 text-xs text-[#0E0F11]">Save</button></div> : <button onClick={() => { setPriceId(item.id); setPriceInput(String(item.ask)); }} className="mono shrink-0 text-[13px] text-[#E8E6E1] hover:text-[#F0A83B]">{money(item.ask)}</button>}</div>)}</div></section>
      <section className="bento-summary rounded-xl border border-[#2A2D31] bg-[#1A1C1F] p-4 md:p-5"><p className="text-[13px] text-[#8B8D91]">Active offer summary</p>{currentOffer ? <><div className="mt-2 flex items-end justify-between gap-4"><div><p className="text-[13px] text-[#8B8D91]">{currentOffer.persona} · round <span className="mono">{currentOffer.round}</span></p><p className="mono mt-1 text-[32px] leading-none text-[#F0A83B]">{money(currentOffer.amount)}</p></div><span className={`mono text-[15px] ${delta < 0 ? 'text-[#F0A83B]' : 'text-[#3DDC84]'}`}>{delta < 0 ? '−' : '+'}{money(Math.abs(delta))} vs ask</span></div><div className="mt-5 grid grid-cols-2 gap-3 border-t border-[#2A2D31] pt-3"><div><p className="text-[13px] text-[#8B8D91]">Ask total</p><p className="mono mt-1 text-[15px]">{money(currentAsk)}</p></div><div><p className="text-[13px] text-[#8B8D91]">Status</p><p className="mt-1 text-[15px] text-[#F0A83B]">{currentOffer.status}</p></div></div></> : <div className="flex min-h-32 items-center text-[15px] text-[#8B8D91]">Waiting for the next offer.</div>}</section>
      {activeDeal && <section className="approval-in bento-approval flex flex-col justify-between gap-4 rounded-xl border border-[#3DDC84]/45 bg-[#1A1C1F] p-4 md:flex-row md:items-center md:px-6"><div><p className="text-[13px] text-[#3DDC84]">Human decision required</p><h2 className="mt-1 text-xl font-semibold">{activeDeal.persona} accepted the deal</h2><p className="mt-1 text-[13px] text-[#8B8D91]">{activeDeal.itemIds.length} item{activeDeal.itemIds.length > 1 ? 's' : ''} · approval token valid for 60 seconds</p></div><div className="flex items-center gap-4"><p className="mono text-[24px] text-[#3DDC84]">{money(activeDeal.amount)}</p><button onClick={() => approve(activeDeal.id)} className="rounded-lg bg-[#3DDC84] px-4 py-3 text-[13px] font-semibold text-[#0E0F11]">Approve deal</button><button onClick={() => { rejectDeal(activeDeal.id); notify('Deal rejected.'); }} className="rounded-lg border border-[#E8564A] px-4 py-3 text-[13px] font-semibold text-[#E8564A]">Reject</button></div></section>}
    </main>
    {notice && <div role="status" className="fixed bottom-5 left-1/2 z-30 -translate-x-1/2 rounded-lg border border-[#2A2D31] bg-[#232629] px-4 py-2.5 text-[13px] text-[#E8E6E1]">{notice}</div>}
    {inspector && <Inspector tools={tools} selectedTool={selectedTool} selectTool={selectTool} toolInput={toolInput} setToolInput={setToolInput} executeTool={executeTool} result={toolResult} close={() => setInspector(false)} />}
  </div>;
}

function FeedMessage({ event, offers, counterInput, setCounterInput, accept, decline, sendCounter }: { event: any; offers: Offer[]; counterInput: Record<string, string>; setCounterInput: (id: string, value: string) => void; accept: (offer: Offer) => void; decline: (offer: Offer) => void; sendCounter: (offer: Offer) => void }) { const offer = event.offerId ? offers.find((item) => item.id === event.offerId) : undefined; const buyer = Boolean(event.persona); return <div className={`message-in flex ${buyer ? 'justify-end' : 'justify-start'}`}><div className={`max-w-[88%] rounded-xl border p-3 ${buyer ? 'border-[#2A2D31] bg-[#232629]' : 'border-[#2A2D31] bg-[#0E0F11]'}`}><div className={`flex items-center gap-2 text-[13px] ${buyer ? 'justify-end' : ''}`}><span style={{ color: buyer ? personaMeta[event.persona]?.color : '#8B8D91' }}>{buyer ? `${personaMeta[event.persona]?.emoji ?? '◌'} ${event.persona}` : '⌁ Your agent'}</span><span className="text-[#8B8D91]">{new Date(event.timestamp).toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' })}</span></div><p className={`mt-2 text-[15px] leading-relaxed ${buyer ? 'text-right' : ''}`}>{event.text}</p>{offer && (offer.status === 'open' || offer.status === 'countered') && <div className="mt-3 border-t border-[#2A2D31] pt-3"><div className={`mono mb-2 text-[15px] ${buyer ? 'text-right' : ''}`} style={{ color: '#F0A83B' }}>{money(offer.amount)} · round {offer.round}</div><div className="flex flex-wrap justify-end gap-2"><button onClick={() => accept(offer)} className="rounded-md bg-[#3DDC84] px-2.5 py-1.5 text-xs text-[#0E0F11]">Accept</button><input aria-label={`Counter ${offer.persona}`} value={counterInput[offer.id] ?? ''} onChange={(event) => setCounterInput(offer.id, event.target.value)} placeholder="Counter" className="mono w-20 rounded-md border border-[#2A2D31] bg-[#0E0F11] px-2 py-1.5 text-xs"/><button onClick={() => sendCounter(offer)} className="rounded-md bg-[#F0A83B] px-2.5 py-1.5 text-xs text-[#0E0F11]">Counter</button><button onClick={() => decline(offer)} className="rounded-md border border-[#E8564A] px-2.5 py-1.5 text-xs text-[#E8564A]">Decline</button></div></div>}</div></div>; }
function Inspector({ tools, selectedTool, selectTool, toolInput, setToolInput, executeTool, result, close }: { tools: any[]; selectedTool: string; selectTool: (name: string) => void; toolInput: string; setToolInput: (value: string) => void; executeTool: () => void; result: string; close: () => void }) { return <div className="fixed inset-0 z-20 bg-black/60" onClick={close}><aside role="dialog" aria-modal="true" aria-label="Tool Inspector" onClick={(event) => event.stopPropagation()} className="absolute inset-y-0 right-0 w-full max-w-xl overflow-y-auto border-l border-[#2A2D31] bg-[#1A1C1F] p-5"><div className="flex items-start justify-between"><div><p className="text-[13px] text-[#8B8D91]">WebMCP tools</p><h2 className="mt-1 text-xl font-semibold">Inspector</h2></div><button aria-label="Close tool inspector" onClick={close} className="text-[15px] text-[#8B8D91]">✕</button></div>{!tools.length ? <p className="mt-6 text-[15px] text-[#8B8D91]">Tools are unavailable until WebMCP is enabled.</p> : <div className="mt-5 grid gap-4 md:grid-cols-[.85fr_1.15fr]"><div className="space-y-1.5">{tools.map((tool) => <button key={tool.name} onClick={() => selectTool(tool.name)} className={`w-full rounded-lg border p-3 text-left ${selectedTool === tool.name ? 'border-[#F0A83B] bg-[#232629]' : 'border-[#2A2D31] bg-[#0E0F11]'}`}><p className="mono text-[13px] text-[#E8E6E1]">{tool.name}</p><p className="mt-1 line-clamp-2 text-[13px] text-[#8B8D91]">{tool.description}</p></button>)}</div><div><p className="mb-2 text-[13px] text-[#8B8D91]">Input JSON</p><textarea aria-label="Tool JSON input" value={toolInput} onChange={(event) => setToolInput(event.target.value)} className="mono h-44 w-full rounded-lg border border-[#2A2D31] bg-[#0E0F11] p-3 text-xs text-[#E8E6E1]"/><button disabled={!selectedTool} onClick={executeTool} className="mt-2 w-full rounded-lg bg-[#F0A83B] py-2.5 text-[13px] font-semibold text-[#0E0F11] disabled:opacity-40">Execute {selectedTool || 'tool'}</button>{result && <pre className="mono mt-3 max-h-72 overflow-auto whitespace-pre-wrap rounded-lg border border-[#2A2D31] bg-[#0E0F11] p-3 text-xs text-[#3DDC84]">{result}</pre>}</div></div>}</aside></div>; }
export default App;
